### ISSUE TITLE
关于Oxford RobotCar Dataset数据集验证集的深度真值

### ISSUE THREAD

**Issue by cojoho** [LINA-lln/ADDS-DepthNet#3]
作者你好，我从你们提供的链接下载到的关于RobotCar验证集深度真值的图片，感觉看上去有很多并不能对应上，或者是有些问题的。比如，下面两个图。
![image](https://user-images.githubusercontent.com/67216764/158511151-aaa0f8c9-3a2e-4400-97a1-564208fe4de2.png)
![image](https://user-images.githubusercontent.com/67216764/158511265-f7d39cf1-53f2-47d8-b807-b50697694898.png)。
我的疑问是，这样的深度真值没问题吗，能起到验证集的作用吗。

**Comment by LINA-lln** [comment]
1. The sensor of the Oxford dataset is 2D-LiDAR, hence some dynamic objects are missed or smeared. And the calibration between color and depth cameras is not accurate enough, so mis-registration exist between image and depth to some extent. You can propose the problem on the official website of the Oxford RobotCar Dataset if they have any solutions.

2. We have carefully selected frames with little errors from the dataset as the validation set.

3. Other similar methods are also validated on this dataset, so to compared equally, we evaluate our approach on this dataset.

**Comment by cojoho** [comment]
Ok，thank you for your response.
