### ISSUE TITLE
About the CUDA memory

### ISSUE THREAD

**Issue by fcntes** [LINA-lln/ADDS-DepthNet#7]
Hi, 
we are very interested in the CUDA memory during training. Could you provide an approximate value of  the GPU memory during training?
Thank you very much!

**Comment by LINA-lln** [comment]
Hi, thanks for your interest in our work. We trained our network on a single 16G GPU with the batch-size of 6.

**Comment by fcntes** [comment]
> Hi, thanks for your interest in our work. We trained our network on a single 16G GPU with the batch-size of 6.

Thank you! 
We would like to know more about the GPU memory usage during training, i.e. how much the train.py takes up exactly, since our GPU is a single 2080Ti with only 11GB.

**Comment by LINA-lln** [comment]
> > Hi, thanks for your interest in our work. We trained our network on a single 16G GPU with the batch-size of 6.
> 
> Thank you! We would like to know more about the GPU memory usage during training, i.e. how much the train.py takes up exactly, since our GPU is a single 2080Ti with only 11GB.

I don't remember the specific GPU memory during training, but it is more than 11G. If you use 11G GPU, you can set smaller batchsize like 3 or 4.

**Comment by fcntes** [comment]
> > > Hi, thanks for your interest in our work. We trained our network on a single 16G GPU with the batch-size of 6.
> > 
> > 
> > Thank you! We would like to know more about the GPU memory usage during training, i.e. how much the train.py takes up exactly, since our GPU is a single 2080Ti with only 11GB.
> 
> I don't remember the specific GPU memory during training, but it is more than 11G. If you use 11G GPU, you can set smaller batchsize like 3 or 4.

Thanks a lot！
