### ISSUE TITLE
About the result of Monodepth2 (Day)

### ISSUE THREAD

**Issue by Yang-Hao-Lin** [LINA-lln/ADDS-DepthNet#8]
Hi

<img width="706" alt="image" src="https://user-images.githubusercontent.com/64567492/184475458-7629a60b-fbc2-4291-953c-f81f7de8bb7a.png">

As shown in your paper, Monodepth2 seems to have better performance than hr-depth,. It makes me a little confused.
Did you use any trick in your training of Monodepth2 (Day)?   THX .

**Comment by LINA-lln** [comment]
Hi, we have not used the tricks with Monodepth2, the performance difference may be caused by dataset changes (KITTI to Oxford).

**Comment by Yang-Hao-Lin** [comment]
Ok. THX for response.

**Comment by Yang-Hao-Lin** [comment]
Ok. THX for response.
